#!/bin/bash
export BASEDIR=$(cd $(dirname "$(readlink -f "$0" || echo "$0")"); pwd)
(
    cat <<tac
{
    "app_name": "Indicator Test",
    "require_gui": "unity macosx",
    "indicator_icons": {
        "startup": "$BASEDIR/icons-%(theme)s/startup.png",
        "normal": "$BASEDIR/icons-%(theme)s/normal.png",
        "working": "$BASEDIR/icons-%(theme)s/working.png",
        "attention": "$BASEDIR/icons-%(theme)s/attention.png",
        "shutdown": "$BASEDIR/icons-%(theme)s/shutdown.png"
    },
    "indicator_menu": [
        {
            "label": "Indicator test",
            "item": "info"
        },{
            "label": "XKCD",
            "item": "xkcd",
            "op": "show_url",
            "args": ["https://xkcd.com/"],
            "sensitive": false
        },{
            "label": "Mailpile",
            "item": "mailpile",
            "op": "show_url",
            "args": ["https://www.mailpile.is/"],
            "sensitive": true
        }
    ]
}
OK LISTEN
tac
echo 'show_splash_screen {"image": "icons-light/normal.png", "message": "Hello world!", "progress_bar": true}'

sleep 2
echo 'update_splash_screen {"progress": 0.2}'
echo 'set_status {"status": "normal"}'

sleep 2
echo 'update_splash_screen {"progress": 0.5, "message": "Woohooooo"}'
echo 'update_splash_screen {"progress": 0.5}'
echo 'set_menu_sensitive {"item": "xkcd"}'
echo 'notify_user {"message": "This is a notification"}'

sleep 2
echo 'update_splash_screen {"progress": 1.0}'
echo 'set_status {"status": "working"}'
sleep 2
echo 'hide_splash_screen {}'
echo 'set_status {"status": "attention"}'

sleep 2
echo 'set_menu_label {"item": "xkcd", "label": "No really, XKCD"}'

sleep 30
echo 'set_status {"status": "shutdown"}'

sleep 5

) | python -m gui_o_matic
