#!/bin/bash
export BASEDIR=$(cd $(dirname "$(readlink -f "$0" || echo "$0")"); pwd)
export PARPID=$$
(
    cat <<tac
{
    "app_name": "Indicator Test",
    "app_icon": "$BASEDIR/img/gt-normal-%(theme)s.png",
    "require_gui": "unity macosx gtk",
    "main_window": {
        "show": false,
        "message": "Hello world!\\nThis is my message for you.",
        "close_quits": true,
        "width": 480,
        "height": 360,
        "image": "$BASEDIR/img/gt-wallpaper.png",
        "actions": [
            {
                "position": "first",
                "label": "XKCD",
                "item": "btn-xkcd",
                "op": "show_url",
                "args": ["https://xkcd.com/"],
                "sensitive": false
            },{
                "position": "first",
                "label": "Mailpile?",
                "item": "mp",
                "op": "terminal",
                "args": {"command": "screen -x -r mailpile || screen"},
                "sensitive": true
            },{
                "position": "first",
                "type": "checkbox",
                "label": "Enable World Peace",
                "item": "ewp",
                "op": "shell",
                "args": ["echo woop woop"],
                "sensitive": true
            },{
                "position": "last",
                "label": "Quit",
                "item": "quit",
                "op": "quit",
                "sensitive": true
            }
        ]
    },
    "indicator": {
        "icons": {
            "startup": "$BASEDIR/img/gt-startup-%(theme)s.png",
            "normal": "$BASEDIR/img/gt-normal-%(theme)s.png",
            "working": "$BASEDIR/img/gt-working-%(theme)s.png",
            "attention": "$BASEDIR/img/gt-attention-%(theme)s.png",
            "shutdown": "$BASEDIR/img/gt-shutdown-%(theme)s.png"
        },
        "menu": [
            {
                "label": "Indicator test",
                "item": "info"
            },{
                "label": "XKCD",
                "item": "menu-xkcd",
                "op": "show_url",
                "args": ["https://xkcd.com/"],
                "sensitive": false
            },{
                "label": "Mailpile",
                "item": "mailpile",
                "op": "show_url",
                "args": ["https://www.mailpile.is/"],
                "sensitive": true
            }
        ]
    }
}
OK LISTEN
tac
echo 'show_splash_screen {"image": "'"$BASEDIR"'/img/gt-splash.png", "message": "Hello world!", "progress_bar": true}'

sleep 2
echo 'update_splash_screen {"progress": 0.2}'
echo 'set_status {"status": "normal"}'

sleep 2
echo 'update_splash_screen {"progress": 0.5, "message": "Woohooooo"}'
echo 'update_splash_screen {"progress": 0.5}'
echo 'set_item_sensitive {"item": "menu-xkcd"}'
echo 'set_item_sensitive {"item": "btn-xkcd"}'
echo 'notify_user {"message": "This is a notification"}'

sleep 2
echo 'update_splash_screen {"progress": 1.0}'
echo 'set_status {"status": "working"}'
sleep 2
echo 'hide_splash_screen {}'
echo 'show_main_window {}'
echo 'set_status {"status": "attention"}'

sleep 2
echo 'set_item_label {"item": "menu-xkcd", "label": "No really, XKCD"}'
echo 'set_item_label {"item": "btn-xkcd", "label": "XKCDonk"}'

sleep 30
echo 'set_status {"status": "shutdown"}'

sleep 5

) | exec python -m gui_o_matic
